### PR TITLE
Add support for login in with user credentials

### PR DESCRIPTION
**Pull request by jjatria**
This patch makes it possible to use the API without a token, by providing either a email / password pair, or a login / password pair, such that this:

```perl
use GitLab::API::v3;

# Also login => $username
my $api = GitLab::API::v3->new(
  url => 'https://gitlab.com/api/v3/',
  email => 'user@email.com',
  password => $password,
);

printf "My user name is %s!\n", $api->current_user->{name};
```

is now possible.

This will make an initial call to `session` before construction, and then cache the token received from the server for all future requests.

### CODE REVIEW

**Comment by bluefeet** [comment]
Looking good, thanks!

**Comment by bluefeet** [comment]
After merging this I took a closer look and saw a different way I'd like this implemented.

So, I changed this all around in 29ab8f029808be0bb53fb3479d092177bca4abf7.

**Comment by jjatria** [comment]
Out of curiosity, why do you prefer this approach?

The only time when you'd need to provide user credentials (or a token) is during object construction. The fact that in this case you need to construct an object, and then call `login` on that object to get _a different object_ doesn't seem to me to be particularly straightforward.

I'd love to hear what sort of use case you had in mind when coming up with this approach.

**Comment by bluefeet** [comment]
Well, I wanted to make it possible to make an anonymous connection, as that is a valid use case and shouldn't be blocked by requiring credentials.  That made me want to maintain the object's immutable design.  Unless the change adds a lot of complexity there is a lot of benefit to get from immutable objects.  Hmm, I've got an idea that may be closer to what you had on the surface.

**Pull request merged**
