### PR TITLE
Won't install due to missing module

### PR DESCRIPTION
**Pull request by nfg**
Hello!

I tried installing under a new install of Perl 5.20.3, and it failed:

    --> Working on GitLab::API::v3
    Fetching http://www.cpan.org/authors/id/B/BL/BLUEFEET/GitLab-API-v3-0.08.tar.gz ... OK
    Configuring GitLab-API-v3-0.08 ... OK
    ==> Found dependencies: Log::Any::Adapter::ScreenColoredLevel
    ! Finding Log::Any::Adapter::ScreenColoredLevel on cpanmetadb failed.
    ! Finding Log::Any::Adapter::ScreenColoredLevel (0) on mirror http://www.cpan.org failed.
    ! Couldn't find module or a distribution Log::Any::Adapter::ScreenColoredLevel
    ! Installing the dependencies failed: Module 'Log::Any::Adapter::ScreenColoredLevel' is not installed
    ! Bailing out the installation for GitLab-API-v3-0.08.

According to the changelog, Log::Any::Adapter::ScreenColoredLevel was renamed to Log::Any::Adapter::Screen (https://metacpan.org/changes/distribution/Log-Any-Adapter-Screen). It looks like the old version was recently unlisted from cpan.

Here's a fix to use the new distribution.

Cheers!

### CODE REVIEW

**Comment by pierre-vigier** [comment]
+1 , Module can't be installed right now because of that, please merge :)

**Comment by agimenez** [comment]
+1 here!

**Comment by LordRafa** [comment]
1+

**Comment by nfg** [comment]
Hello! Is there anything I can do to get this merged?

**Comment by bluefeet** [comment]
Merged!  Thanks.

**Comment by nfg** [comment]
Woohoo! Thank you!

**Comment by pierre-vigier** [comment]
Thanks!

**Pull request closed without merging**
