### PR TITLE
Add the search_user method

### PR DESCRIPTION
**Pull request by SkySymbol**

### CODE REVIEW

**Comment by agimenez** [comment]
Hey! looks useful, is it planned to be merged?

Thanks,
L. Alberto

**Comment by bluefeet** [comment]
I don't see this API endpoint anywhere in the documentation:
http://docs.gitlab.com/ce/api/users.html
Can you explain?

Also, the `lib/GitLab/API/v3.pm` module should never be edited directly as it is completely auto-generated.  Please see:
https://github.com/bluefeet/GitLab-API-v3/blob/master/author/README.pod

**Comment by agimenez** [comment]
Within the link you posted (http://docs.gitlab.com/ce/api/users.html), search for "search". you will find the text inside "Users -> List Users -> For Admins".

The specific text is:

> You can search for users by email or username with: /users?search=John

Thank you!

**Comment by bluefeet** [comment]
There is already support for parameters in the ->users() method.  Something like this should work:

```
my $users = $api->users({search=>...});
```

Does that do what you need?

**Comment by SkySymbol** [comment]
This is what I need, thanks. I can't test your code right now but that should do the trick. My PR is quite useless then.

**Pull request closed without merging**
