### PR TITLE
Change API path for single MR

### PR DESCRIPTION
**Pull request by trunov-ms**
Append MR GitLab API changes

### CODE REVIEW

**Comment by bluefeet** [comment]
Note that you shouldn't ever edit `lib/GitLab/API/v3.pm`.  All the code in there is auto-generated.  Instead see `author/README.pod`.

Also, the API documentation still says that it is `merge_requests` not `merge_request`.  Can you provide details as to why you think this change is needed (are the docs out-of-date???).
http://docs.gitlab.com/ce/api/merge_requests.html

**Comment by trunov-ms** [comment]
Both variant `merge_request` and `merge_requsts `are working now.
But in January only `merge_request`  worked

**Comment by bluefeet** [comment]
Maybe you were on a slightly out-of-date version of GitLab and they changed it to `merge_requests` but left `merge_request` for backwards compatibility?  :-/

**Comment by trunov-ms** [comment]
I don't know.
In 6.x version worked merge_requests for methods for single MR , in 7.x  merge_request only,
Now in GitLab 8.7.3 are working both version

**Pull request closed without merging**
