### PR TITLE
Add request tests (RFC)

### PR DESCRIPTION
**Pull request by jjatria**
Inspired by the failing tests in #29, this patch adds a different offline set of tests.

Instead of sending a request to a running GitLab server and processing the response, the new `t/requests.t` test sends the requests to a custom `Plack` app that simply sends the data from the request back. So the tests do not test how the response is parsed, but how the request is built.

The test is not complete at this point, and comments are welcome.

Some of the seemingly unrelated changes are there to allow for this kind of testing to take place. In particular, since some methods do not return anything, a custom file logger is used to send the request data to a temporary file. To make this work, `GitLab::API::v3` now makes use of a logger of category `GitLab`, to separate logging streams.

Adding these tests revealed some paths that seem to be wrong in the spec, as well as an unnecessary leading slash that was added to the paths. This patch includes fixes for these as well.

### CODE REVIEW

**Comment by bluefeet** [comment]
Allright, this is the last PR in the queue.  Once this one is resolved I'll be ready to move onto v4.  Could you resolve the conflicts and then I'll review?

**Comment by jjatria** [comment]
Done! Look forward to your comments :rocket:

**Comment by bluefeet** [comment]
Hey man - this one is still having issues.  Finally getting v4 going today.  If you get a chance to take another look at this that'd be great.  The one issue I found is that `Hash::Merge::Simple` isn't declared in the cpanfile (and probably a few other things which I coincidentally already had like `lack::App::TestServer::Echo`).  I like the direction this is going.  In v4 I'm focusing on making live tests uses a GitLab docker container, but only for testing different classes of tests (like a basic GET/POST, etc) to test that the fundamentals are working.  Tests like what you have here are great for more unit-style tests.  So, this PR will definitely be useful.

**Comment by bluefeet** [comment]
And, FYI, here's my output at the end of a final run of `requests.t`:

```
#   Failed test 'no (unexpected) warnings (via done_testing)'
#   at t/requests.t line 682.
# Looks like you failed 168 tests of 502.
t/requests.t ........... Dubious, test returned 168 (wstat 43008, 0xa800)
Failed 168/502 subtests
```

**Comment by bluefeet** [comment]
I won't be adding this to the v3 module.  Please open a pull request over at:
https://github.com/bluefeet/GitLab-API-v4
If you want to continue this development.

**Comment by jjatria** [comment]
Hi! Sorry I took so long to respond. These messages caught me between jobs.

About this PR: I am not certain what is the best way to test a client tat communicates with an external server. I certainly don't think that we should be testing against a live server (and personally, I'm not convinced about the idea of going with a Docker container). I came up with `Plack::App::TestServer::Echo` (which is actually not on CPAN, it only exists in `t/`) as a way to catch what the client was sending (since what the server responds is no really our concern).

And that failing test you got... that seems to be from an unexpected warning. What was the warning? Since writing these tests, I've lost all my appreciation for `Test::Warnings` because of just this.

In any case, I'm fine with these tests not being used if you have some other idea, but I definitely think that f422976 at least deserves cherry-picking, since those are paths that are just broken, and that I only realised were broken because of these tests.

I do think I'd like to see these sort of tests being used, though, so I might port them over to `v4` when I get the time. If for nothing else than they might reveal some more typos in the paths. :)

(FYI: I've rebased this against master, and cleared things up a little. The current version of this branch lives <https://github.com/jjatria/GitLab-API-v3/tree/request-tests>.

**Comment by bluefeet** [comment]
Hey man, sorry I missed this.  All ongoing development is now on `v4` which now (finally) has a set of unit tests which work without a GitLab install.  Right now its all embedded in `t/unit.t` but could definitely be extended and generalized (and I don't currently have a good reason to do it).  I don't think one set of tests is any less valid than the other, regression and unit tests both have their purpose.  Later!

**Pull request closed without merging**
